language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE taskmanagement;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

services:
  - mysql

script:
  - vendor/bin/phpunit